pipelines:
  default:
    - step:
        name: Sync GitHub
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/dostmonitoringsystem/auditing-team-monitoring-systems.git
          - cd auditing-team-monitoring-systems.git
          - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE"@github.com/AmaroJoenard152/Auditing-Team-Monitoring-System.git
